services:
    test-bot:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: test-bot
        env_file: .env
        environment:
            DB_TYPE: postgres
            DB_HOST: test-bot-postgres
            DB_PORT: 5432 # Ichki port, PostgreSQL uchun default port
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
        ports:
            - '127.0.0.1:3000:3000' # Tashqi port:3999, ichki port:3999
        networks:
            - postgres
        restart: unless-stopped

networks:
    postgres:
        driver: bridge # Custom network for communication between services

